# Generated by Django 4.2.27 on 2025-12-15 16:48

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('hourly_fee', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Court',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('court_type', models.CharField(choices=[('INDOOR', 'Indoor'), ('OUTDOOR', 'Outdoor')], max_length=10)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('equipment_type', models.CharField(choices=[('RACKET', 'Racket'), ('SHOES', 'Shoes')], max_length=10)),
                ('total_quantity', models.PositiveIntegerField()),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PricingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('rule_type', models.CharField(choices=[('PEAK_HOURS', 'Peak Hours Premium'), ('WEEKEND', 'Weekend Premium'), ('INDOOR_PREMIUM', 'Indoor Court Premium'), ('EQUIPMENT_FEE', 'Equipment Rental Fee'), ('COACH_FEE', 'Coach Fee')], max_length=20)),
                ('multiplier', models.DecimalField(decimal_places=2, default=1.0, help_text='Multiplier for percentage-based rules (e.g., 1.5 for 50% increase)', max_digits=5)),
                ('flat_fee', models.DecimalField(decimal_places=2, default=0, help_text='Flat fee to add (for equipment, coach, etc.)', max_digits=10)),
                ('is_percentage', models.BooleanField(default=True, help_text='If true, applies multiplier; if false, adds flat fee')),
                ('is_enabled', models.BooleanField(default=True)),
                ('priority', models.IntegerField(default=0, help_text='Lower numbers are applied first')),
                ('start_time', models.TimeField(blank=True, help_text='For peak hours rules', null=True)),
                ('end_time', models.TimeField(blank=True, help_text='For peak hours rules', null=True)),
                ('applies_to_days', models.CharField(blank=True, help_text="Comma-separated day numbers (0=Mon, 6=Sun). E.g., '5,6' for weekends", max_length=20)),
            ],
            options={
                'ordering': ['priority', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CoachAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_slots', to='booking.coach')),
            ],
            options={
                'verbose_name_plural': 'Coach Availabilities',
                'ordering': ['coach', 'day_of_week', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_breakdown', models.JSONField(default=dict, help_text='Detailed breakdown of pricing rules applied')),
                ('status', models.CharField(choices=[('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled')], default='CONFIRMED', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('coach', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='booking.coach')),
                ('court', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='booking.court')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-start_time'],
            },
        ),
        migrations.CreateModel(
            name='BookingEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment_items', to='booking.booking')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.equipment')),
            ],
            options={
                'unique_together': {('booking', 'equipment')},
            },
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['date', 'start_time', 'end_time'], name='booking_boo_date_cbeb2a_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['court', 'date'], name='booking_boo_court_i_3f84e5_idx'),
        ),
    ]
